sudo: required
services:
  - docker

before_install:
  - docker build -t pkaranthaker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pkaranthaker/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-198280591345"
  bucket_path: "docker-react"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
